# Generated by Django 5.2.9 on 2026-05-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('ANNUAL', 'Annual'), ('SICK', 'Sick'), ('CASUAL', 'Casual'), ('COMPENSATORY', 'Compensatory'), ('WFH', 'Work From Home')], max_length=50),
        ),
    ]
